language: cpp
os: osx

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

script:
  - cd linux
  - make

addons:
  artifacts: true

deploy:
  provider: releases
  file: ag.dylib
  skip_cleanup: true
  draft: true
