name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CC: gcc-${{ matrix.gcc-ver }}
      CXX: g++-${{ matrix.gcc-ver }}
    strategy:
      fail-fast: false
      matrix:
        gcc-ver: [6, 7, 8]
        configuration: [Release, Debug]
        
    runs-on: ubuntu-18.04

    steps:
    - name: Setup
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get -y install g++-${{ matrix.gcc-ver }} g++-${{ matrix.gcc-ver }}-multilib gcc-${{ matrix.gcc-ver }}-multilib gcc-${{ matrix.gcc-ver }} linux-libc-dev-i386-cross mesa-common-dev ninja-build rapidjson-dev
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: linux/
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: linux/release/
