name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Update system
        run: sudo apt update
      - name: Install G++ (multilib)
        run: sudo apt install -y g++-multilib
      - name: Build
        run: cd linux && CFG=release make
      - name: Deploy
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Linux-x86
          path: |
            linux/release/ag.so
            linux/release/ag.so.dbg
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: MSBuild.exe projects/vs2019/projects.sln /p:Configuration=Release /p:Platform=Win32
      - name: Deploy
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Win32
          path: |
            projects/vs2019/Release/agdll/ag.dll
            projects/vs2019/Release/agdll/ag.pdb
